#!/bin/bash
line=$(wc -l 1.txt | awk '{print $1}')

if [[ $1 = "" ]];then
    echo "usage: todo <init|list|add|edit|remove|reset|mark|remark> [args]"
    fi

if [[ $1 = "init" ]];then
    touch 1.txt | echo "Initialized successfully" 
    fi

if [[ $1 = "add" ]];then
    echo "1. ${*:2}" >> 1.txt
    fi

if [[ $1 = "edit" && $2 -le $line ]];then
    sed -i "$2c 1. ${*:3}" 1.txt
    fi
if [[ $1 = "edit" && $2 -gt $line ]];then
    echo "Task not found"
    fi

if [[ $1 = "remove" ]];then
    echo ${*:2}
    sed -i "$2"d 1.txt
    fi

if [[ $1 = "mark" ]];then
    sed -n $2p 1.txt | sed s/1./2./g | cat >>1.txt | sed -i $2d 1.txt
    fi

if [[ $1 = "unmark" ]];then
    sed -n $2p 1.txt | sed s/2./1./g | cat >>1.txt | sed -i $2d 1.txt
    fi

if [[ $1 = "list" ]];then
    awk -F. '{print NR $2}' 1.txt
    fi
  